-- データベース作成
CREATE DATABASE `auth_db`;

-- DB選択
USE `auth_db`;

-- ユーザー作成
CREATE USER `hoge` IDENTIFIED BY 'development';

-- 権限追加
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE ON `auth_db`.* TO `hoge` identified by 'development';

